CCK: Reconcile rules
cucumber/compatibility-kit pull request #76
Opened 2023-10-13 08:53 UTC by luke-hill

`rules` is now is consistent for ruby/js.

I also massively removed the contradictory steps. Now it's at least consistent.

### ⚡️ What's your motivation? 

Goes towards completion of issue in tracker

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

2023-10-13 08:53 UTC, luke-hill commented
@davidjgoss think my knowledge of the `assert` library might be a bit lacking here. This will probably need a fix. I couldn't find a `beEmpty()` function

2023-10-31 13:42 UTC, davidjgoss requested changes

2023-10-31 13:42 UTC, davidjgoss commented on devkit/samples/rules/rules.feature.ts
> +    this.chocolate = this.stock.pop
This is referencing a method without calling it. I think it needs to be:

```ts
this.chocolate = this.stock.pop()
```

2023-10-31 13:42 UTC, davidjgoss commented on devkit/samples/rules/rules.feature.ts
> +  assert(this.chocolate).notToBe(null)
```ts
assert.ok(this.chocolate)
```

2023-10-31 13:42 UTC, davidjgoss commented on devkit/samples/rules/rules.feature.ts
> +  assert(this.chocolate).toBe(null)
```ts
assert.strictEqual(this.chocolate, undefined)
```

2023-10-31 13:42 UTC, davidjgoss commented on devkit/samples/rules/rules.feature.ts
> +  if(this.money > price) {
I guess the check should really be `this.money >= price`?

2023-10-31 16:41 UTC, davidjgoss approved these changes

2023-10-31 17:19 UTC, merged